#!/usr/bin/env node
/**
 * Regenerates the auto-managed repository catalog in README.md between the
 * repo-catalog markers from the live GitHub API. Runs locally or in CI
 * (GITHUB_TOKEN recommended to avoid anonymous rate limits).
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const OWNER = 'leonardoxr';
const START = '<!-- repo-catalog:start -->';
const END = '<!-- repo-catalog:end -->';
const readmePath = fileURLToPath(new URL('../README.md', import.meta.url));

/** @type {Record<string, string>} */
const headers = {
  Accept: 'application/vnd.github+json',
  'X-GitHub-Api-Version': '2022-11-28',
  'User-Agent': OWNER + '-profile-readme',
};
const token = process.env.GITHUB_TOKEN || process.env.GH_TOKEN;
if (token) headers.Authorization = 'Bearer ' + token;

async function api(path) {
  const res = await fetch('https://api.github.com' + path, { headers });
  if (!res.ok) throw new Error(path + ' -> HTTP ' + res.status + ': ' + (await res.text()));
  return res.json();
}

// Fetch every public repository (paginated).
const repos = [];
for (let page = 1; ; page++) {
  const chunk = await api('/users/' + OWNER + '/repos?per_page=100&page=' + page);
  repos.push(...chunk);
  if (chunk.length < 100) break;
}

const pub = repos.filter((r) => !r.private && !r.archived);
const byName = (name) => pub.find((r) => r.name.toLowerCase() === name.toLowerCase());
const recentFirst = (a, b) => String(b.pushed_at).localeCompare(String(a.pushed_at));

const aggregate = byName('dsh-plugins');
if (!aggregate) throw new Error('dsh-plugins not found among public repositories');
const plugins = pub
  .filter((r) => r.name.toLowerCase().startsWith('dsh-') && !r.fork && r.name !== 'dsh-plugins')
  .sort(recentFirst);
const relatedForks = pub
  .filter((r) => r.fork && /^(dsh|deepseek)/i.test(r.name))
  .sort(recentFirst);

const describe = (r) => (r.description || '').trim() || '_No description yet._';

/** @type {string[]} */
const out = [];
out.push(START);
out.push('<!-- Generated by scripts/generate-repos.mjs -- do not edit by hand. -->');
out.push('');
out.push('### \u{1F4E6} [' + aggregate.name + '](' + aggregate.html_url + ') \u2014 the all-in-one bundle');
out.push('');
out.push('One install wires up the whole collection: this repository publishes **dsh-all-in-one**, an aggregate bundle that mounts every plugin below as a single layer, keeping each plugin\u2019s canonical row ID so existing config overrides survive the migration.');
out.push('');
out.push('```sh');
out.push('dsh plugin --profile <name> add dsh-all-in-one');
out.push('```');
out.push('');
out.push('### \u{1F50C} Plugins (' + plugins.length + ')');
out.push('');
out.push('| Plugin | What it does | Language |');
out.push('| --- | --- | --- |');
for (const p of plugins) {
  out.push('| [' + p.name + '](' + p.html_url + ') | ' + describe(p) + ' | ' + (p.language || '\u2014') + ' |');
}
out.push('');

if (relatedForks.length > 0) {
  out.push('### \u{1F34D} Related forks');
  out.push('');
  for (const f of relatedForks) {
    out.push('- [' + f.name + '](' + f.html_url + ') \u2014 ' + describe(f));
  }
  out.push('');
}

out.push('---');
out.push('');
out.push('_Auto-refreshed ' + new Date().toISOString().slice(0, 10) + ' UTC from the GitHub API by [.github/workflows/update-repos.yml](https://github.com/' + OWNER + '/' + OWNER + '/blob/main/.github/workflows/update-repos.yml)._');

out.push('');
out.push(END);

const body = out.join('\n') + '\n';
const md = await readFile(readmePath, 'utf8');
const startIdx = md.indexOf(START);
const endIdx = md.indexOf(END);
if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
  throw new Error('repo-catalog markers missing from README.md');
}
await writeFile(readmePath, md.slice(0, startIdx) + body + md.slice(endIdx + END.length));
console.log('Catalog refreshed:', plugins.length, 'plugins,', relatedForks.length, 'related forks');
